# Generated by Django 5.0.6 on 2024-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
