# Generated by Django 5.0.6 on 2024-06-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chat_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/app/chat_pictures/'),
        ),
    ]
