# Generated by Django 5.0.6 on 2024-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmodel_chat_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
