# Generated by Django 5.0.6 on 2024-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chat_files',
            field=models.FileField(blank=True, null=True, upload_to='static/app/chat_files/'),
        ),
    ]
